### ISSUE TITLE
Test time tracker

### ISSUE THREAD

**Issue by atmmoreira** [atmmoreira/jobsinworld#36]

**Comment by renydev** [comment]
Oi Anderson.

Eu usei SMTP pq já estava configurado no meu software, posso fazer tbm por
API, sem problemas.

O nosso site https://www.arrojoimobiliaria.com.br/

A princípio não enviarei e-mail marketing, será só para envio de extrato de
clientes.

Por mês serão no máximo 100 emails, é algo bem pequeno.

[]`s


Em qua., 8 de mai. de 2024, 07:52, Anderson Martins <
***@***.***> escreveu:

**Comment by atmmoreira** [comment]
Desculpa @renydev Mas nao entendi o comentário, rsss.
