### ISSUE TITLE
Separar em arquivos por países

### ISSUE THREAD

**Issue by trofinomelissa** [atmmoreira/jobsinworld#5]
A lista tem crescido, creio que seria interessante separar em arquivos por países.
O que acha?

Posso mudar isso e mandar a sugestão para ver.

**Comment by atmmoreira** [comment]
Pode ser... vamos ver como fica.... é porque não queria complicar para o acesso....
Ou não sei se criar um HTML, enfim.

**Comment by trofinomelissa** [comment]
Acho que seria interessante uma referência a outro arquivo .md mesmo.

Exemplo: https://help.github.com/articles/basic-writing-and-formatting-syntax/#relative-links

**Comment by atmmoreira** [comment]
blza...
